           main: main.ms
          title: JSON
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: core ui uix
    orientation: portrait
 remote-console: 
        version: 1.0
